### ISSUE TITLE
RuntimeError invalid count

### ISSUE THREAD

**Issue by johnjohndoe** [peleteiro/progressbar#15]
I using the following Ruby script to download a few files. The progress bar visualizes the process.

```ruby
#!/usr/bin/env ruby

require 'open-uri'
require 'progressbar'
require 'net/http'
require 'uri'

def http_download(uri, filename)
  pbar = nil
  uri.open(
        read_timeout: 500,
        content_length_proc: lambda { |t|
        if t && 0 < t
          pbar = ProgressBar.new("...", t)
          pbar.file_transfer_mode
        end
        },
        progress_proc: lambda {|s|
          pbar.set s if pbar
        }) do |file|
    open filename, 'w' do |io|
      file.each_line do |line|
        io.write line
      end
    end
  end
end
```

[One of the files](http://paloalto.opendata.junar.com/datastreams/73029-palo-alto-population-by-ethnicity.csv) I want to download I get the following RuntimeError:

```
/home/user/.rvm/gems/ruby-2.1.1@global/gems/progressbar-0.21.0/lib/progressbar.rb:271:in `set': 
    invalid count: 466 (total: 252) (RuntimeError)| ETA:  --:--:--

    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:331:in `call'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:331:in `block (3 levels) in open_http'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:407:in `call_block'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:398:in `<<'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:369:in `block (2 levels) in inflate_adapter'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:368:in `inflate'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:368:in `block in inflate_adapter'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:407:in `call_block'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:398:in `<<'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:106:in `read'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:390:in `read'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:284:in `block in read_body_0'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:260:in `inflater'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:274:in `read_body_0'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:328:in `block (2 levels) in open_http'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1415:in `block (2 levels) in transport_request'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:162:in `reading_body'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1378:in `request'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:319:in `block in open_http'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:313:in `open_http'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
    from /home/user/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/open-uri.rb:704:in `open'
```

If you have tipps how to simplify the method code (progress-bar configuration) that would be helpful too.

**Comment by peleteiro** [comment]
Progressbar will merge with [ruby-progressbar](https://github.com/jfelchner/ruby-progressbar) soon.

**Comment by johnjohndoe** [comment]
Any details about the merge?

**Comment by peleteiro** [comment]
You can use ruby-prograssbar gem today or wait until the next major release later this week.
